server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/busticketbookingdb?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ccnhan1288@gmail.com
    password: cofi hvpk uhah wiuv
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: false



