server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/busticketbookingdb?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ccnhan1288@gmail.com
    password: cofi hvpk uhah wiuv
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: false

jwt:
  secret: BusTicketBookingApplicationSecretKey123456789012345678901234567890
  expiration: 86400

cloudinary:
  cloud-name: dcobbjewc
  api-key: 469351546516413
  api-secret: NhYKyxjf-WyUJTDA9pxO60VR3Z4


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web.servlet: DEBUG
    com.example.BusTicketBookingBackend: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
